# Generated by Django 3.1.4 on 2020-12-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewShow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=50)),
                ('release', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
